---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1tee4k8zmq99lq0p8lpn9xzk7tl78c60g086zq9u83tlphrkx2fms25clux"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1tee4k8zmq99lq0p8lpn9xzk7tl78c60g086zq9u83tlphrkx2fms25clux"
stores:
  yaml:
    indent: 2
